name: flutter_app
description: A professional Flutter app with Splash, Login, and Home screens.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_lints: ^5.0.0
  get: ^4.7.2
  provider: ^6.1.5
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    # - assets/pics.jpg  # Add your logo here for the splash screen if needed
    # - assets/insta1.png
    # - assets/insta2.png